"""test end

Revision ID: 8ddb9cd07aca
Revises: a14a3dd67333
Create Date: 2023-02-02 15:26:01.179855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ddb9cd07aca'
down_revision = 'a14a3dd67333'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('message_contacts_chat_id_fkey', 'message_contacts', type_='foreignkey')
    op.drop_column('message_contacts', 'chat_id')
    op.add_column('messages', sa.Column('chat_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'messages', 'messages', ['chat_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'chat_id')
    op.add_column('message_contacts', sa.Column('chat_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('message_contacts_chat_id_fkey', 'message_contacts', 'messages', ['chat_id'], ['id'])
    # ### end Alembic commands ###
